### ISSUE TITLE
Installation failure due to incorrect pep 508 format. 

### ISSUE THREAD

**Issue by zyone1991** [logic-star-ai/swt-bench#3]
### Describe the bug

pip install fails with the following error:  

>  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      configuration error: `project.optional-dependencies.figures[3]` must be pep508
      DESCRIPTION:
          Project dependency specification according to PEP 508
      GIVEN VALUE:
          "git+https://github.com/nielstron/venny4py.git"
      OFFENDING RULE: 'format'
      DEFINITION:
          {
              "$id": "#/definitions/dependency",
              "title": "Dependency",
              "type": "string",
              "format": "pep508"
          }

This error is occurring because the package specification in your pyproject.toml file doesn't follow PEP 508 format for dependency specifications. 

To fix this, consider changing in pyproject.toml "git+https://github.com/nielstron/venny4py.git" -> "venny4py @ git+https://github.com/nielstron/venny4py.git"

### Steps/Code to Reproduce

pip install -e .

### Expected Results

install successfully

### Actual Results

installation failed

**Comment by nielstron** [comment]
Resolved as of bcaada78e1956c7ad764e616a31f44f561644138
